# Generated by Django 3.2.25 on 2024-12-13 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_totpdevice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TOTPDevice',
        ),
    ]
