# Generated by Django 5.1.3 on 2024-12-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_auditlog_options_userprofile_is_admin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=100)),
                ('mount_point', models.CharField(max_length=255)),
                ('total', models.BigIntegerField()),
                ('used', models.BigIntegerField()),
                ('free', models.BigIntegerField()),
                ('percent_used', models.FloatField()),
                ('fs_type', models.CharField(max_length=50)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
